name: Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/releases/*"
          token: ${{ secrets.GITHUB_TOKEN }}
